Repository status-im/open-bounty, pull requests merged in 2018-03, with the labels that each got.

#332 Update repo name when processing issue/PR webhooks
  resources/sql/queries.sql
  src/clj/commiteth/db/repositories.clj
  src/clj/commiteth/routes/services.clj
  src/clj/commiteth/routes/webhooks.clj
Labels: Tested-OK

#341 [Fix #339] Update GitHub comment in deploy-pending-contracts scheduler thread
  resources/sql/queries.sql
  src/clj/commiteth/bounties.clj
  src/clj/commiteth/db/issues.clj
  src/clj/commiteth/github/core.clj
  src/clj/commiteth/scheduler.clj
Labels: Tested-Issues

#370 Don't show `Manage Payouts` unless user has issued bounties
  src/cljs/commiteth/core.cljs
Labels: Tested-OK, org-dashboard

#383 Iterate through return value of extract-issue-number instead of always picking first
  src/clj/commiteth/routes/webhooks.clj
Labels: Tested-OK
